### PR TITLE
LRDOCS-9666 Add language key override example for 7.4+

### PR DESCRIPTION
**Pull request by jhinkey**
I created a separate example for 7.4+, and left the 7.3- example in place.
- It overrides the `home=` language key.
- I removed the ranking since the default ranking is "0", which is higher than DXP's default ranking "-1"

### CODE REVIEW

**Comment by jhinkey** [comment]
Need to test this more.

**Comment by jhinkey** [comment]
It's all good.

**Comment by brianchandotcom** [comment]
@jhinkey 

1.) I think we can do an empty

docs/dxp/latest/en/liferay-internals/extending-liferay/overriding-global-language-keys/resources/liferay-i1f4.zip/i1f4-impl/build.gradle

Or we may even be able to delete it

Please try and resend

2.) Also, instead of i1f4, make it i2f4

just easier to read because the 1 and the i look similar.

**Comment by jhinkey** [comment]
OK will do.

**Pull request closed without merging**
