### PR TITLE
LRDOCS-8890 LRDOCS-8916 setup_tutorial.sh: Check for Yarn. Check Windows-specific NPM locations for node modules and node binaries

### PR DESCRIPTION
**Pull request by jhinkey**
The Fragments Toolkit uses Yarn now. I modified setup_tutorial.sh to install the `yarn` module using `npm` and install the `generator-liferay-fragments` module to Yarn's global default location  `~/.config/yarn/global/node_modules`.

cc @sez11a

https://issues.liferay.com/browse/LRDOCS-8890

### CODE REVIEW

**Comment by jhinkey** [comment]
@p2kmgcl - Pablo, here are the changes to the setup script.

**Comment by jhinkey** [comment]
@brianchandotcom 

I added Windows-specific checks for node module binaries and dependencies, because their locations are different on Windows:

-     Binaries are at {prefix}/
-     Node modules are at {prefix}/node_modules

The Windows locations are explained in https://docs.npmjs.com/cli/v6/configuring-npm/folders#node-modules

**Comment by brianchandotcom** [comment]
@jhinkey violates DRY.

Set ${NPM_CONFIG_PREFIX}/bin and ${NPM_CONFIG_PREFIX}/lib as local function variables.

@p2kmgcl fyi.

**Comment by brianchandotcom** [comment]
@jhinkey see 98705398bae0ce42764a03eb30937b3761465e4a

**Comment by jhinkey** [comment]
Thanks,  @brianchandotcom . I'll add local variables to handle the locations for node modules and binaries.

**Pull request closed without merging**
