### PR TITLE
LRDOCS-8961 Code for 'Using Default Synchronous Messaging'

### PR DESCRIPTION
**Pull request by jhinkey**

### CODE REVIEW

**Comment by jhinkey** [comment]
I'll resend with after renaming the OSGi Commands class.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/7cadb8b33c...30905ddfa2

**Comment by brianchandotcom** [comment]
@jhinkey I made a lot of changes. Please review.

**Comment by jhinkey** [comment]
Will do. Thanks!

**Pull request closed without merging**
