### PR TITLE
forms-search 7.x | fix ddm sample as per feedback | LRDOCS-8191

### PR DESCRIPTION
**Pull request by rbohl**
re-send with logging added to initial sample.
 https://issues.liferay.com/browse/LRDOCS-8191

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@rbohl a few more changes;

1.) Please change

json-wrapper to r2f1

and for the language key, call it R2F1

I just want to limit the number of ideas.

2.) The link to https://github.com/liferay/liferay-portal/blob/7.3.1-ga2/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/storage/DDMJSONStorageAdapter.java

Please add a task to rename DDMJSONStorageAdapter.java to JSONDDMStorageAdapter.java after GA6 is released in a few days/weeks.

3.) 7.3.1-ga2 is hard coded. Can you change it to something like [$LIFERAY_LEARN_DXP_VERSION$]

And then search and replace that version when we call "build_site.sh"?

I wanted to call it LIFERAY_LEARN_* to ensure we never conflict it with sample code.

Thx.

**Comment by brianchandotcom** [comment]
actually, one edit..

json-wrapper should be r2f1-ddm-storage-adapter

Language key should be

r2f1-ddm-storage-adapter=R2F1 Dynamic Datap Mapping Storage Adapter

I think that ties the ideas more clearly. Otherwise, I may think it scraped it from the bnd.bnd file.

**Comment by rbohl** [comment]
1. Changed the Language.properties using the key from your edit, and updated the article text to reflect that key. Will re-send the branch.

2. Tracking the change of the JSON adapter name here: https://issues.liferay.com/browse/LRDOCS-8296

3. Using a variable for the DXP version in our GitHub links: I propose to do this in a separate PR, as I'll need to coordinate with other writers who have hard-coded links to our github tags, so I can make sure they don't need a specific tag but can accept the default version we define for the variable.

**Comment by rbohl** [comment]
Re-sent here: https://github.com/brianchandotcom/liferay-learn/pull/48

**Comment by rbohl** [comment]
Git tag variable work here: https://github.com/brianchandotcom/liferay-learn/pull/49

**Pull request closed without merging**
