### PR TITLE
LRDOCS-8982 Invoking Actions with MVCPortlet

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-8982

### CODE REVIEW

**Comment by jhinkey** [comment]
I'm not sure why this is failing the build. The build had a timeout ...
`npm ERR! request to https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz failed, reason: Socket timeout`

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/918c8b56a3...f899d69a32

**Comment by brianchandotcom** [comment]
@jhinkey I think I found a bug.

See my clean up in 81dc85c7 and my fix in f899d69a

**Comment by jhinkey** [comment]
You're absolutely right, @brianchandotcom . Sorry I meant to map to the name used in the annotation, just like you corrected it to.

**Pull request closed without merging**
