### PR TITLE
buildscript: install wheel

### PR DESCRIPTION
**Pull request by rbohl**
I'd like your advice Brian. JR built on Windows and saw an error that a Python packaging tool wasn't installed, `wheel`. sphinx-intl needs it, but declaring it before sphinx packages of course wrecks our sorting. So, do we install out of sort order or do something else? You can see one solution here, but I don't like it since it duplicates the line. I'm Interested to see how you would solve this. Not necessarily expecting you to merge this in.

### CODE REVIEW

**Comment by rbohl** [comment]
https://packaging.python.org/discussions/wheel-vs-egg/

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/96fb694d27...61a9bd53c7

**Comment by brianchandotcom** [comment]
@rbohl see 61a9bd53c70f2fd77a44d78a8b455d3ba65dd72a

**Comment by rbohl** [comment]
Nice, that's a better solution.

**Pull request closed without merging**
