### PR TITLE
LRDOCS-8134 Use global Gradle cache

### PR DESCRIPTION
**Pull request by sez11a**
Removed one line of code from gradlew to make this work. @jrhoun

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/dc2c36bd22...34a6d03311

**Comment by brianchandotcom** [comment]
@sez11a can you find the latest and greatest "gradlew" from Gradle and compare it to what we have? Can we use that one instead?

@petershin fyi  - this is just for our examples.

**Comment by sez11a** [comment]
Here's a diff; on the left is Gradle's original; on the right is ours (prior to this change). @petershin could tell us why they were necessary: 
image

**Comment by petershin** [comment]
@sez11a - The only difference I saw between `5.6.4` vanilla and the one used by Liferay is the line that was removed in https://github.com/brianchandotcom/liferay-learn/commit/34a6d033114aff693f921808134142b2950df9d1.  The advantages of setting the Gradle user home directory are:

- the `gradle.properties` file can be added to the same directory and can be committed to GitHub
- the properties are consistent for all users

Regarding https://github.com/brianchandotcom/liferay-learn/commit/34a6d033114aff693f921808134142b2950df9d1, this line would also need to be removed from `gradlew.bat`

**Pull request closed without merging**
