### PR TITLE
LRDOCS-7658 code example x8f3 for Overriding Global Language Properties

### PR DESCRIPTION
**Pull request by jhinkey**
https://issues.liferay.com/browse/LRDOCS-7658
cc @mtokudome

Note, the package and class names are based on the convention used for 
`liferay-portal/modules/dxp/apps/akismet/akismet-web/src/main/java/com/liferay/akismet/internal/lang/EnUsResourceBundle.java`

* **_package:_** com.acme.x8f3.internal.**lang**
* **_class:_** X8F3**EnUsResourceBundle**.java

Note: you must use a separate class per local you want to override. For example, X8F3**EsEsResourceBundle**.java to override language keys for users from Spain.

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/0dbc1f326a...c89e025264

**Comment by brianchandotcom** [comment]
@jhinkey initial code commit by @mtokudome did not have a JIRA ticket

See 9e92a73ae9c2b7dc9179434695a2917f06392236 and c89e025264bba4e61a1e57a10a36108c5748017a

Can you also add a Portuguese and Japanese example? Thx.

**Comment by brianchandotcom** [comment]
@jhinkey @mtokudome add Portuguese and Japanese to the same bundle. Thx. And show how if you pick Chinese, it defaults to English because no Chinese one was set.

Thx.

**Comment by jhinkey** [comment]
@brianchandotcom I'm confused about your comment on the user picking Chinese. Wouldn't the Chinese `publish` language key https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/content/Language_zh_CN.properties#L3832 be used?

**Comment by jhinkey** [comment]
@brianchandotcom Are you referring to when we add a language key for some but no all locales?

For example, we add language key `foo` for
1. the default locale (i.e., via Language.properties)
2. other specific locales (e.g., Portuguese and Japanese)

When a user selects a locale (e.g., Chinese) that doesn't have the language key, the language key for the default locale is used.

**Comment by brianchandotcom** [comment]
My bad @jhinkey 

I didn't realize you were just overriding a key. I thought you were adding a new key, but you're just overriding it. But can you still add one for Portuguese or Spanish? Thx.

**Comment by mtokudome** [comment]
@brianchandotcom Yes, I can add a Portuguese and Japanese example to the bundle.

**Pull request closed without merging**
