### PR TITLE
LRDOCS-8912 build_site.sh: Drop .zip from the leading dir in the ZIP file

### PR DESCRIPTION
**Pull request by jhinkey**
Hi Brian,

We can't use `unzip liferay-xxxx.zip` on our current ZIP files because the leading dir (with the same name as the ZIP file) clashes with the ZIP file.

> $ unzip liferay-r1s1.zip
Archive:  liferay-r1s1.zip 
checkdir error:  liferay-r1s1.zip exists but is not directory 
                 unable to process liferay-r1s1.zip/. 

By dropping `.zip` from the leading directory name in the ZIP file, executing `unzip liferay-xxxx.zip` extracts the contents, all of which is in a leading folder named `liferay-xxxx`. 

Also, I cleaned up the output_dir_name logic because ALL or our liferay-xxxx.zip dirs are in now in `resources/` parent dirs. 

https://issues.liferay.com/browse/LRDOCS-8912

cc @rbohl

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jhinkey any way to make this less code? I switched to 7z to make this a 1 liner change.

See https://superuser.com/questions/340046/creating-an-archive-from-a-directory-without-the-directory-name-being-added-to-t

**Comment by jhinkey** [comment]
@brianchandotcom 

We could drop .zip from all of the liferay-xxxx.zip project dir names. That way we we could zip up the project dir into liferay-xxxx.zip and the unzipped dir doesn't conflict with the ZIP file.

* ZIP file: liferay-xxxx.zip
* Unzipped dir: liferay-xxxx

Here's proposed code:
```bash
		for proj_dir_name in $(find build/input/"${product_version_language_dir_name}" -name liferay-[a-z][0-9][a-z][0-9] -type d)
		do
			pushd ${proj_dir_name}

			local zip_file_prefix=$(basename "${proj_dir_name}")

			7z a ${zip_file_prefix}.zip ../${zip_file_prefix}\

			local output_dir_name=$(dirname "${proj_dir_name}")

			output_dir_name=$(dirname "${output_dir_name}")
			output_dir_name=$(dirname "${output_dir_name}")
			output_dir_name=${output_dir_name/input/output}

			popd

			mkdir -p "${output_dir_name}"

			mv "${proj_dir_name}"/"${zip_file_prefix}".zip "${output_dir_name}"
		done
```

What do you think?

**Comment by rbohl** [comment]
@jhinkey  and I were just slacking about this @brianchandotcom . 

Depending on how we want to skin this, there's a one-line addition that leverages 7-zip's `rn` (rename) command, and it appears to do what we need:
```bash
7z rn ${zip_file_name} ${zip_file_name} ${zip_file_name%.*} 
```

If you add it directly after the current 7z command `7z a ${zip_file_name} ...` it renames the root inside the archive, dropping the `.zip`.

I can also see the logic in renaming the src project folders to drop `.zip` as Jim proposed. It'd be slightly more work to refactor things, but perhaps a more transparent fix.

**Comment by jhinkey** [comment]
Guys, I'm going to send a new PR with the command @rbohl proposed. Later, if we want, we can revisit dropping .zip from the project folders. Thanks.

**Pull request closed without merging**
