### PR TITLE
LRDOCS-0 Python Black

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/bf6f7f8ec9...38ace788be

**Comment by brianchandotcom** [comment]
@petershin @hhuijser we need to improve our SF for Python, see 38ace788be791becc1a4fad90fbf7b16d908dc28

The Python code in com-liferay-osb-asah-private is MUCH better. I don't know if it's because we also use a Facebook Python prettier or if @marcellustavares has just been very careful with the code.

But to scale, we need our Python code looking clean.

@hhuijser @petershin can you guys fix this? Thanks! This is higher priority because we're going to do be doing more and more Python because of AI/machine learning/Spark.

@holatuwol fyi

**Comment by petershin** [comment]
@marcellustavares - Were you manually sorting the method names (`def`) alphabetically and removing trailing new lines?  When I ran `yapf` it didn't automatically fix it.

**Comment by marcellustavares** [comment]
yes, I've been doing this manually.

**Comment by petershin** [comment]
Ok, I'll take a look at the other python formatting tools.

If there are no tools that can automatically make these changes, we may need to look into adding a PythonSourceProcessor in SF

**Pull request closed without merging**
