### PR TITLE
LRDOCS-7774 Using Localized Messages in an MVC Portlet

### PR DESCRIPTION
**Pull request by jhinkey**
cc @mtokudome

This portlet uses its own localized messages and Liferay's `success` localized message.

### CODE REVIEW

**Comment by mtokudome** [comment]
I found that this example seems to work even without the line `"javax.portlet.supported-locale=en_US,ja,pt_BR",`

**Comment by jhinkey** [comment]
Thanks for bringing that up. I think we should add that line back in though. I'm getting a sneaking suspicion it's needed, even if it's to communicate to the system "Hey, I have translations for these locales. If you try to use anything else, you'll get my default locale".

**Comment by jhinkey** [comment]
@mtokudome Would you add that property back and force push?

**Comment by jhinkey** [comment]
Also, would you sort each Language* file's keys?

**Comment by jhinkey** [comment]
Sorry, I meant the previous comment for LRDOCS-7770 PR.

**Comment by jhinkey** [comment]
I'll resend with the `supported-locale` line.

**Pull request closed without merging**
