### PR TITLE
LRDOCS-8703 Rename *Greeting classes to *Greeter

### PR DESCRIPTION
**Pull request by jhinkey**
cc @sez11a

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/67e7af4d94...2eb2d5eeaf

**Comment by brianchandotcom** [comment]
Nice. There's a reference to reeting in

docs/dxp/7.x/en/system-administration/installing-and-managing-apps/managing-apps/blacklisting-apps.md

Looks off to me.

Thx @jhinkey @sez11a fyi

**Comment by jhinkey** [comment]
@brianchandotcom Yep, for blacklisting an app and module I showed the Marketplace app and a greeting api module. These are arbitrary--we don't use any example ZIP in the article. I can the screenshot and text to com.acme.greeter.

**Comment by jhinkey** [comment]
I'll take care of it in https://issues.liferay.com/browse/LRDOCS-8706

**Pull request closed without merging**
