### PR TITLE
liferay-learn 7.x | add a parent dir to the zips

### PR DESCRIPTION
**Pull request by rbohl**
resend of https://github.com/brianchandotcom/liferay-learn/pull/123
refactored to use 7z to create .zip archives, using a parent dir named identically to the archive. cc @jhinkey

### CODE REVIEW

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/62998c8228...a707618414

**Comment by brianchandotcom** [comment]
@rbohl I merged this, but did you test this on Linux or just Windows?

**Comment by rbohl** [comment]
only tested on linux--i can ask jr to try it out windows

cc @jrhoun

**Comment by jrhoun** [comment]
Works fine for me on both windows (git bash) and WSL -- I had to install it for both, but otherwise its ok.

**Pull request closed without merging**
