### PR TITLE
LRDOCS-9544 portlet level configuration

### PR DESCRIPTION
**Pull request by jhinkey**
Makoto's description is helpful here:

> This is starting off with the same codebase as Portlet Preferences ([P1Z2 Portlet](https://github.com/liferay/liferay-learn/tree/master/docs/dxp/latest/en/developing-applications/developing-a-java-web-application/using-mvc/portlet-preferences/resources/liferay-p1z2.zip/p1z2-web)) but adding a configuration interface so that a UI appears in system settings.
>
> The expected behavior is that a user can set a default color in system settings (green, orange, purple) so that when the portlet is deployed, this selection will show up by default. But once a user selects a portlet preference (blue, red, yellow), that choice will supersede the system settings.

cc @mtokudome

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jhinkey 

what's the purpose of

```
<aui:input name="<%= Constants.CMD %>" type="hidden" value="<%= Constants.UPDATE %>" />
```

I see us setting it but not reading it anywhere

@mtokudome fyi

**Comment by jhinkey** [comment]
@brianchandotcom Dave Nebinger helped us discover that SettingsConfigurationAction.processAction method requires the UPDATE command. If it doesn't find it, it simply returns without processing the action.

https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/portlet/SettingsConfigurationAction.java#L103-L107

**Comment by jhinkey** [comment]
@brianchandotcom If you don't include that input, the preference doesn't stick.

**Comment by brianchandotcom** [comment]
Merged. Thank you.
View total diff: https://github.com/brianchandotcom/liferay-learn/compare/7f18c65147...fd7b3cf2df

**Comment by brianchandotcom** [comment]
My bad @jhinkey see 783740773b72bd71922c7a19f35c89c2e68da8fa

**Pull request closed without merging**
